export const DOM_ALUNO_NOME = "#span_MPW0041vPRO_PESSOALNOME";

export const DOM_ALUNO_RA = "#span_MPW0041vACD_ALUNOCURSOREGISTROACADEMICOCURSO";

export const DOM_ALUNO_SEMESTRE = "#span_MPW0041vACD_ALUNOCURSOCICLOATUAL";

export const DOM_ALUNO_EMAIL_INSTITUCIONAL = "#span_vINSTITUCIONALFATEC";

export const DOM_ALUNO_EMAIL = "#span_vPRO_PESSOALEMAIL";

export const DOM_ALUNO_CPF = "#span_vPRO_PESSOALDOCSCPF";

export const DOM_ALUNO_DATA_NASCIMENTO = "#span_vPRO_PESSOALDATANASCIMENTO";

export const DOM_ALUNO_NOME_CURSO = "#span_vACD_CURSONOME_MPAGE";

export const DOM_ALUNO_PERIODO = "#span_vACD_PERIODODESCRICAO_MPAGE";

export const DOM_FORM_INPUT_USUARIO = "#vSIS_USUARIOID";

export const DOM_FORM_INPUT_SAIDA_ERROS = "#span_vSAIDA";

export const DOM_GXSTATE = "input[name='GXState']";

export const DOM_ALUNO_CONTAINER_MATERIAS = ".ygtvc21 span";